import type { CSSProperties } from "react";

export const s = {
  overlay: { position: "fixed", inset: 0, display: "flex", justifyContent: "flex-end", zIndex: 50 } satisfies CSSProperties,
  backdrop: { position: "absolute", inset: 0, background: "rgba(0,0,0,0.45)" } satisfies CSSProperties,
  panel: {
    position: "relative",
    width: 720,
    maxWidth: "94%",
    background: "var(--bg-surface)",
    borderLeft: "1px solid var(--border-strong)",
    boxShadow: "var(--shadow-drawer)",
    display: "flex",
    flexDirection: "column",
  } satisfies CSSProperties,
  header: {
    display: "flex",
    alignItems: "flex-start",
    gap: 14,
    padding: "18px 24px",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  headText: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  title: {
    fontSize: 16,
    fontWeight: 700,
    letterSpacing: "-0.01em",
    wordBreak: "break-all",
    margin: 0,
  } satisfies CSSProperties,
  subtitle: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
    fontSize: 13,
    color: "var(--text-secondary)",
    marginTop: 6,
  } satisfies CSSProperties,
  closeBtn: {
    display: "inline-grid",
    placeItems: "center",
    width: 30,
    height: 30,
    borderRadius: 6,
    border: "1px solid transparent",
    background: "transparent",
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  body: { flex: 1, overflow: "auto", padding: 24, fontSize: 14 } satisfies CSSProperties,
  state: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 12,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  skeleton: { display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
} as const;
